# Generated by Django 3.2.22 on 2023-10-31 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo_electronico', models.CharField(max_length=200, unique=True)),
                ('contrasenha', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PROGRESO', 'PROGRESO'), ('COMPLETADA', 'COMPLETADA')], default='PENDIENTE', max_length=10)),
                ('completada', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
                ('hora_vencimiento', models.TimeField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='gestion_tareas.usuario')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.proyecto')),
                ('usuarios_asignados', models.ManyToManyField(related_name='usuarios_asignados', through='gestion_tareas.Asignacion_Tarea', to='gestion_tareas.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_proyecto', to='gestion_tareas.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyectos_asignados',
            field=models.ManyToManyField(related_name='proyectos_asignados', to='gestion_tareas.Usuario'),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('etiquetas_asociadas', models.ManyToManyField(to='gestion_tareas.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.usuario')),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion_tarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.tarea'),
        ),
        migrations.AddField(
            model_name='asignacion_tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tareas.usuario'),
        ),
    ]
